version: "3"
services:
  php:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "smart_door"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "password"
